export default defineEventHandler(() => {
    return {
        offers: [
            {
                id: Math.floor(Math.random() * 10000),
                offerType: 'AUCTION',
                title: 'Дерево',
                city: 'Санкт-Петербург, Красное Село',
                seller: 'Торговый Дом ГОСТ',
                productType: 'Стройматериалы',
                description: 'Пиломатериалы брус доска. Распродажа пиломатериалов в связи закрытием ЛЕСО-БАЗЫ!\n' +
                    'Успейте приобрести пиломатериал со скидками до закрытия 01.06.2022 !\n',
                price: 11000 ,
                quantity: 3,
                image: '/images/offer1.jpeg',
                status: 'STOCK',
                liked: false,
            },
            {
                id: Math.floor(Math.random() * 10000),
                offerType: 'DIRECT',
                title: 'Шифер',
                city: 'Санкт-Петербург, Красное Село',
                seller: 'Торговый Дом ГОСТ',
                productType: 'Стройматериалы',
                description: 'Пиломатериалы брус доска. Распродажа пиломатериалов в связи закрытием ЛЕСО-БАЗЫ!\n' +
                    'Успейте приобрести пиломатериал со скидками до закрытия 01.06.2022 !\n',
                price: 11000 ,
                quantity: 3,
                image: '/images/offer2.jpg',
                status: 'STOCK',
                liked: false,
            },
            {
                id: Math.floor(Math.random() * 10000),
                offerType: 'AUCTION',
                title: 'Фанера',
                city: 'Санкт-Петербург, Красное Село',
                seller: 'Торговый Дом ГОСТ',
                productType: 'Стройматериалы',
                description: 'Пиломатериалы брус доска. Распродажа пиломатериалов в связи закрытием ЛЕСО-БАЗЫ!\n' +
                    'Успейте приобрести пиломатериал со скидками до закрытия 01.06.2022 !\n',
                price: 11000 ,
                quantity: 3,
                image: '/images/offer3.jpg',
                status: 'BAG',
                liked: false,
            },
            {
                id: Math.floor(Math.random() * 10000),
                offerType: 'DIRECT',
                title: 'Кирпич',
                city: 'Санкт-Петербург, Красное Село',
                seller: 'Торговый Дом ГОСТ',
                productType: 'Стройматериалы',
                description: 'Пиломатериалы брус доска. Распродажа пиломатериалов в связи закрытием ЛЕСО-БАЗЫ!\n' +
                    'Успейте приобрести пиломатериал со скидками до закрытия 01.06.2022 !\n',
                price: 11000 ,
                quantity: 3,
                image: '/images/offer4.jpg',
                status: 'BAG',
                liked: false,
            },
            {
                id: Math.floor(Math.random() * 10000),
                offerType: 'AUCTION',
                title: 'Цемент',
                city: 'Санкт-Петербург, Красное Село',
                seller: 'Торговый Дом ГОСТ',
                productType: 'Стройматериалы',
                description: 'Пиломатериалы брус доска. Распродажа пиломатериалов в связи закрытием ЛЕСО-БАЗЫ!\n' +
                    'Успейте приобрести пиломатериал со скидками до закрытия 01.06.2022 !\n',
                price: 11000 ,
                quantity: 3,
                image: '/images/offer5.jpg',
                status: 'BAG',
                liked: false,
            },
            {
                id: Math.floor(Math.random() * 10000),
                offerType: 'DIRECT',
                title: 'Трубы',
                city: 'Санкт-Петербург, Красное Село',
                seller: 'Торговый Дом ГОСТ',
                productType: 'Стройматериалы',
                description: 'Пиломатериалы брус доска. Распродажа пиломатериалов в связи закрытием ЛЕСО-БАЗЫ!\n' +
                    'Успейте приобрести пиломатериал со скидками до закрытия 01.06.2022 !\n',
                price: 11000 ,
                quantity: 3,
                image: '/images/offer6.jpg',
                status: 'STOCK',
                liked: false,
            },
        ],
    }
});